kind: Service
apiVersion: v1
metadata:
  name: website-service
spec:
  type: NodePort
  selector:
    app: website-service
  ports:
  - protocol: TCP
    targetPort: 8001
    port: 8001
    nodePort: 30801

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-service-deployment
  labels:
    app: website-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website-service
  template:
    metadata:
      labels:
        app: website-service
    spec:
      containers:
      - name: website-service
        image: satyendrasingh/website:0.$BUILD_NUMBER
        ports:
        - containerPort: 8001


