kind: Service
apiVersion: v1
metadata:
  name: book-service
spec:
  type: ClusterIP
  selector:
    app: book-service
  ports:
  -  port: 8060
     targetPort: 8060

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
  labels:
    app: book-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: satyendrasingh/book:0.$BUILD_NUMBER
        ports:
        - containerPort: 8060
